/* ============================================================
   Kaaty — Content data: Products, Solutions, Integrations
   ============================================================ */

const SHARED_BENEFIT_FAQS = [
  { q: 'Can I start with just this and add more later?', a: 'Yes. Every Kaaty module works standalone and snaps into the rest of the platform whenever you’re ready — no migration, no re-training.' },
  { q: 'Does it work with my existing hardware?', a: 'Kaaty runs on any Android or desktop device and integrates natively with Pine Labs smart terminals, thermal and kitchen printers, and barcode scanners.' },
  { q: 'How long does onboarding take?', a: 'Most outlets go live the same week. We handle menu setup, data import and staff training so there’s zero downtime.' },
];

/* ============================== PRODUCTS ============================== */
const PRODUCTS = {
  'pos': { name: 'Kaaty POS', icon: 'monitor', group: 'Restaurant Operations', visual: 'pos',
    title: 'Billing built for peak-hour speed',
    sub: 'Run frictionless checkouts, split tabs, and capture every cash and UPI sale instantly — online and offline.',
    features: [
      { title: 'Express counter billing', mock: 'pos', desc: 'A layout tuned so billers move at full speed during the rush.', points: ['Favourites, combos and modifiers one tap away.', 'Auto-printed itemised KOTs and token slips.'] },
      { title: 'Offline-first reliability', mock: 'business', desc: 'Keep selling even when the internet drops — nothing is ever lost.', points: ['Works fully offline and syncs when back online.', 'Unbroken logs across pre-orders and walk-ups.'] },
      { title: 'Anti-fraud UPI confirmation', mock: 'pos', desc: 'End fake-screenshot scams with real-time payment verification.', points: ['Live UPI ledger confirmation at the counter.', 'Nothing marked paid until the money lands.'] },
      { title: 'Live inventory sync', mock: 'kds', desc: 'Stock updates the moment an item sells, across every screen.', points: ['Auto-deduct ingredients per recipe.', 'Low-stock alerts right on the billing screen.'] },
    ],
    benefits: [{ icon: 'zap', label: 'Sub-second billing' }, { icon: 'wifi-off', label: 'Offline ready' }, { icon: 'printer', label: 'Pine Labs & printers' }, { icon: 'shield-check', label: 'Fraud-proof UPI' }, { icon: 'refresh-cw', label: 'Real-time sync' }, { icon: 'layers', label: 'Multi-outlet ready' }],
  },
  'kds': { name: 'Kaaty KDS', icon: 'chef-hat', group: 'Restaurant Operations', visual: 'kds',
    title: 'Kitchen management without the chaos',
    sub: 'Route every item to the right station, track prep in real time, and clear the rush with a visual, icon-driven display.',
    features: [
      { title: 'Smart station routing', mock: 'kds', desc: 'Each item lands at exactly the station that cooks it.', points: ['Route by category, course or kitchen.', 'Balance load across stations automatically.'] },
      { title: 'Single-tap milestones', mock: 'pos', desc: 'Move tickets from Preparing to Ready in one tap.', points: ['Colour-coded states everyone understands.', 'Auto-notify the counter and customer.'] },
      { title: 'Cross-channel queue', mock: 'kds', desc: 'Dine-in, online and QR orders in one unified queue.', points: ['No missed tickets across channels.', 'Priority and prep-time aware ordering.'] },
      { title: 'Bump, recall & timers', mock: 'business', desc: 'Keep service tight with live prep timers and recall.', points: ['Per-ticket timers flag slow orders.', 'Instant recall of bumped tickets.'] },
    ],
    benefits: [{ icon: 'route', label: 'Station routing' }, { icon: 'timer', label: 'Live prep timers' }, { icon: 'layers', label: 'All channels in one' }, { icon: 'hand', label: 'Single-tap control' }, { icon: 'bell', label: 'Auto notifications' }, { icon: 'monitor', label: 'Any screen size' }],
  },
  'mobile-app': { name: 'Kaaty Mobile App', icon: 'smartphone', group: 'Customer Experience', visual: 'phone',
    title: 'Let customers order before they arrive',
    sub: 'A branded native ordering app with live tracking and push notifications that eliminate customer lines entirely.',
    features: [
      { title: 'Your own branded app', mock: 'phone', desc: 'A customer ordering channel that puts your brand front and centre.', points: ['Responsive digital menus with images.', 'Commission-free, direct-to-you orders.'] },
      { title: 'Real-time order tracking', mock: 'phone', desc: 'Keep customers informed at every stage automatically.', points: ['Placed → Preparing → Ready updates.', 'Accurate, live pickup countdowns.'] },
      { title: 'Push notifications', mock: 'phone', desc: 'Ping customers the exact second an order is ready.', points: ['Order-ready and offer notifications.', 'Win-back nudges for lapsed customers.'] },
      { title: 'Secure digital payments', mock: 'business', desc: 'Direct integration with modern payment rails.', points: ['UPI, cards and wallets supported.', 'Pre-paid wallet for quick checkout.'] },
    ],
    benefits: [{ icon: 'smartphone', label: 'Native iOS & Android' }, { icon: 'bell', label: 'Push notifications' }, { icon: 'map-pin', label: 'Live tracking' }, { icon: 'wallet', label: 'Pre-paid wallet' }, { icon: 'palette', label: 'Fully branded' }, { icon: 'percent', label: 'Zero commission' }],
  },
  'business': { name: 'Kaaty Business App', icon: 'layout-dashboard', group: 'Business Management', visual: 'business',
    title: 'Complete control, from anywhere',
    sub: 'The owner’s command centre — live sales, margins, multi-outlet analytics and vendor settlements in your pocket.',
    features: [
      { title: 'Live sales velocity', mock: 'business', desc: 'See exactly how every outlet is performing, right now.', points: ['Real-time revenue and order trends.', 'Margin and product performance views.'] },
      { title: 'Multi-outlet aggregation', mock: 'business', desc: 'Every branch rolled up into one clean dashboard.', points: ['Compare outlets side by side.', 'Role-based access for managers.'] },
      { title: 'Automated settlements', mock: 'pos', desc: 'Vendor splits and payouts reconciled for you.', points: ['Commission and rent handled per vendor.', 'Transparent, dispute-free payouts.'] },
      { title: 'Reports on the go', mock: 'phone', desc: 'Pull any statement from your phone, anytime.', points: ['80+ exportable reports.', 'Daily summaries pushed to you.'] },
    ],
    benefits: [{ icon: 'trending-up', label: 'Live analytics' }, { icon: 'layers', label: 'Multi-outlet' }, { icon: 'wallet', label: 'Auto settlements' }, { icon: 'file-text', label: '80+ reports' }, { icon: 'smartphone', label: 'On the go' }, { icon: 'lock', label: 'Role-based access' }],
  },
  'vendor': { name: 'Kaaty Vendor App', icon: 'store', group: 'Business Management', visual: 'pos',
    title: 'A full POS in every vendor’s pocket',
    sub: 'A lightweight mobile checkout for small stalls and counters — no expensive hardware, no complex setup.',
    features: [
      { title: 'Hardware-free billing', mock: 'pos', desc: 'A complete digital checkout on any phone or tablet.', points: ['No desktop terminal required.', 'Bluetooth printer support built in.'] },
      { title: 'Mobile checkout anywhere', mock: 'phone', desc: 'Bill customers from wherever the queue forms.', points: ['Android and iOS supported.', 'UPI and card payments on device.'] },
      { title: 'Lightweight inventory', mock: 'business', desc: 'Track ingredient depletion without the overhead.', points: ['Simple stock counts and alerts.', 'Mark items out of stock instantly.'] },
      { title: 'Code-free onboarding', mock: 'kds', desc: 'Launch a new stall in minutes, not days.', points: ['Guided, no-code setup.', 'Clone menus from existing stalls.'] },
    ],
    benefits: [{ icon: 'smartphone', label: 'No hardware needed' }, { icon: 'zap', label: 'Minutes to launch' }, { icon: 'printer', label: 'Bluetooth printing' }, { icon: 'package', label: 'Lite inventory' }, { icon: 'store', label: 'Per-stall ledger' }, { icon: 'refresh-cw', label: 'Synced to owner' }],
  },
  'token-board': { name: 'Kaaty Token Board', icon: 'tv', group: 'Restaurant Operations', visual: 'kds',
    title: 'Clear the crowd with live token displays',
    sub: 'Dual-state TV notification boards synced to your kitchen — guests always know when their order is up.',
    features: [
      { title: 'Dual-state display', mock: 'kds', desc: 'Preparing and Ready columns guests read at a glance.', points: ['Big, legible tokens from across the room.', 'Auto-advance as the kitchen bumps tickets.'] },
      { title: 'Kitchen-synced in real time', mock: 'kds', desc: 'The board reflects exactly what the KDS shows.', points: ['Zero manual updates.', 'Instant move from preparing to ready.'] },
      { title: 'Multi-screen support', mock: 'business', desc: 'Run boards across counters, halls and pickup points.', points: ['Independent screens per zone.', 'Central control of all displays.'] },
      { title: 'On-brand displays', mock: 'phone', desc: 'Your logo, colours and promos between updates.', points: ['Custom branding and theming.', 'Rotate offers and announcements.'] },
    ],
    benefits: [{ icon: 'tv', label: 'TV-ready' }, { icon: 'refresh-cw', label: 'Kitchen-synced' }, { icon: 'eye', label: 'Highly legible' }, { icon: 'layers', label: 'Multi-screen' }, { icon: 'palette', label: 'Branded' }, { icon: 'megaphone', label: 'Promo slots' }],
  },
  'qr-ordering': { name: 'QR Ordering', icon: 'qr-code', group: 'Customer Experience', visual: 'qr',
    title: 'Scan. Order. Enjoy.',
    sub: 'Let guests order from their table with a simple scan — fewer lines, faster turns, and higher ticket values.',
    features: [
      { title: 'Scan-to-order in seconds', mock: 'qr', desc: 'Guests browse, order and pay from their own phone.', points: ['No app download required.', 'Orders flow straight to the kitchen.'] },
      { title: 'No more lines', mock: 'kds', desc: 'Eliminate counter crowding at the busiest times.', points: ['Self-service from tables and benches.', 'Staff freed up to serve.'] },
      { title: 'Smart upsell', mock: 'qr', desc: 'Automated recommendations lift average order value.', points: ['Add-on and combo prompts.', 'Most-loved item suggestions.'] },
      { title: 'Live table management', mock: 'business', desc: 'See every table’s orders and status in real time.', points: ['Table-wise order history.', 'Merge, move and split with ease.'] },
    ],
    benefits: [{ icon: 'qr-code', label: 'No app needed' }, { icon: 'trending-up', label: '+ ticket value' }, { icon: 'users', label: 'Less crowding' }, { icon: 'utensils-crossed', label: 'Table-aware' }, { icon: 'zap', label: 'Instant to kitchen' }, { icon: 'wallet', label: 'Pay at table' }],
  },
  'kiosk': { name: 'Self Ordering Kiosk', icon: 'scan-line', group: 'Customer Experience', visual: 'kiosk',
    title: 'Cut queue time by up to 80%',
    sub: 'Interactive self-service terminals that speed up throughput and boost ticket sizes during high-volume periods.',
    features: [
      { title: 'Self-service terminals', mock: 'kiosk', desc: 'Guests order themselves on a fast, friendly touchscreen.', points: ['Visual, image-rich menus.', 'Accessible, multi-language ready.'] },
      { title: 'Automated cross-sell', mock: 'kiosk', desc: 'Smart prompts grow every order — without staff effort.', points: ['Combo and add-on suggestions.', 'Proven uplift in average ticket.'] },
      { title: 'Integrated payments', mock: 'pos', desc: 'Card and digital payments via attached hardware.', points: ['Tap, card and UPI on the kiosk.', 'Instant printed or digital receipts.'] },
      { title: 'Error-free orders', mock: 'kds', desc: 'Exactly what the guest selected reaches the kitchen.', points: ['No mishears at the counter.', 'Faster, more accurate service.'] },
    ],
    benefits: [{ icon: 'scan-line', label: 'Line-busting' }, { icon: 'trending-up', label: 'Bigger tickets' }, { icon: 'credit-card', label: 'Pay on kiosk' }, { icon: 'check', label: 'Order accuracy' }, { icon: 'languages', label: 'Multi-language' }, { icon: 'smile', label: 'Better experience' }],
  },
};
const PRODUCT_GROUPS = [
  { label: 'Restaurant Operations', items: ['pos', 'kds', 'token-board'] },
  { label: 'Customer Experience', items: ['mobile-app', 'qr-ordering', 'kiosk'] },
  { label: 'Business Management', items: ['business', 'vendor', 'inventory-link'] },
];

/* ============================== SOLUTIONS ============================== */
const SOLUTIONS = {
  'college-canteens': { name: 'College Canteens', icon: 'graduation-cap', visual: 'qr',
    title: 'Built for high-volume campus dining',
    sub: 'Eliminate fake payment screenshots, crush the lunch-rush lines, and run closed-loop student wallets across campus.',
    rows: [
      { title: 'Anti-fraud UPI confirmation', mock: 'pos', desc: 'Where Kaaty began — kill fake-screenshot scams for good.', points: ['Real-time UPI ledger confirmation.', 'Nothing marked paid until money lands.'] },
      { title: 'Closed-loop student wallets', mock: 'phone', desc: 'Pre-loaded campus wallets speed up every transaction.', points: ['Top-up once, tap-to-pay all week.', 'Parents and admins see spend clearly.'] },
      { title: 'QR & pre-ordering', mock: 'qr', desc: 'Students order ahead and skip the line entirely.', points: ['Scan-to-order from anywhere on campus.', 'Pickup tokens clear the counter crowd.'] },
    ] },
  'restaurants': { name: 'Restaurants', icon: 'utensils-crossed', visual: 'business',
    title: 'A 5-star restaurant experience awaits',
    sub: 'Make dine-in effortless with table management, course-by-course KOT routing, and guest CRM built for restaurants.',
    rows: [
      { title: 'Table & reservation management', mock: 'kds', desc: 'Merge, move and split table orders with ease.', points: ['Record table-wise orders accurately.', 'Assign tables by live availability.'] },
      { title: 'Course & KOT control', mock: 'pos', desc: 'Fire courses in sequence to the right stations.', points: ['Sequential course firing.', 'Split and transfer KOTs without re-punching.'] },
      { title: 'Guest CRM & loyalty', mock: 'phone', desc: 'Recognise regulars and bring them back automatically.', points: ['Profiles with visit history.', 'Targeted offers and rewards.'] },
    ] },
  'cafes': { name: 'Cafes', icon: 'coffee', visual: 'pos',
    title: 'Run your café like clockwork',
    sub: 'Fast bar billing, recipe-level inventory, and loyalty that keeps your regulars coming back for one more cup.',
    rows: [
      { title: 'Quick bar billing', mock: 'pos', desc: 'Speed through the morning rush with a café-tuned layout.', points: ['Milk, shots and syrup modifiers in a tap.', 'Quick-pay wallet for regulars.'] },
      { title: 'Recipe-level inventory', mock: 'business', desc: 'Track every gram of beans and litre of milk.', points: ['Auto-deduct ingredients as items sell.', 'Low-stock alerts before you run dry.'] },
      { title: 'Loyalty & re-engagement', mock: 'phone', desc: 'Bring guests back with points and timely nudges.', points: ['Automated rewards on every visit.', 'Win-back offers for lapsed guests.'] },
    ] },
  'food-courts': { name: 'Food Courts', icon: 'store', visual: 'business',
    title: 'One platform for the whole food court',
    sub: 'Centralise dozens of independent stalls under a single parent ledger — unified tokens, settlements and reporting.',
    rows: [
      { title: 'Multi-vendor management', mock: 'business', desc: 'Onboard every stall and run them as one system.', points: ['Each vendor gets a lightweight POS.', 'Owner sees consolidated performance.'] },
      { title: 'Unified token system', mock: 'kds', desc: 'One token journey no matter how many stalls.', points: ['Single token across vendors.', 'Central TV boards for the court.'] },
      { title: 'Automated settlements', mock: 'pos', desc: 'Splits and payouts reconciled automatically.', points: ['Commission and rent per vendor.', 'Transparent, dispute-free.'] },
    ] },
  'cloud-kitchens': { name: 'Cloud Kitchens', icon: 'cloud', visual: 'kds',
    title: 'Manage every brand from one screen',
    sub: 'Run multiple virtual brands across all aggregators on one POS — accept, prep and dispatch without app-shuffling.',
    rows: [
      { title: 'Virtual brand management', mock: 'business', desc: 'Multiple cloud-kitchen brands, cleanly segregated.', points: ['Manage all brands in one setup.', 'One POS, no extra charge.'] },
      { title: 'Aggregator aggregation', mock: 'kds', desc: 'End the shuffle between a dozen ordering apps.', points: ['Accept all channels in one click.', 'Bill and KOT from one place.'] },
      { title: 'Dispatch coordination', mock: 'phone', desc: 'Keep dispatch tight so food leaves hot.', points: ['Live order stage to handover.', 'Rider assignment synced to kitchen.'] },
    ] },
  'hotels': { name: 'Hotels', icon: 'bed-double', visual: 'business',
    title: 'Hospitality-grade F&B operations',
    sub: 'Run room service, multiple dining outlets and banquets on one connected platform with room-folio billing.',
    rows: [
      { title: 'Room-folio billing', mock: 'pos', desc: 'Post F&B charges straight to the guest room folio.', points: ['Seamless room-charge posting.', 'Consolidated checkout billing.'] },
      { title: 'Multi-outlet dining', mock: 'business', desc: 'Restaurant, bar, café and room service as one.', points: ['Unified menus across outlets.', 'Central reporting for the property.'] },
      { title: 'Banquet & event orders', mock: 'kds', desc: 'Handle large covers and pre-set menus with ease.', points: ['Event-wise order planning.', 'Kitchen coordination at scale.'] },
    ] },
  'bakeries': { name: 'Bakeries', icon: 'croissant', visual: 'pos',
    title: 'Sweeten your bakery operations',
    sub: 'Weight-based billing, batch production planning, and ingredient-level inventory tailored for bakeries.',
    rows: [
      { title: 'Weight & unit billing', mock: 'pos', desc: 'Bill by piece, weight or box — accurately every time.', points: ['Integrated weighing-scale support.', 'Mixed-unit carts handled cleanly.'] },
      { title: 'Production & batch planning', mock: 'business', desc: 'Plan daily bakes against demand and stock.', points: ['Forecast batches from trends.', 'Track consumption per recipe.'] },
      { title: 'Custom cake pre-orders', mock: 'phone', desc: 'Take advance orders with deposits and pickups.', points: ['Capture custom requests.', 'Automated pickup reminders.'] },
    ] },
  'ice-cream-parlours': { name: 'Ice Cream Parlours', icon: 'ice-cream-cone', visual: 'kiosk',
    title: 'Scoop up faster service',
    sub: 'Speed through dessert rushes with quick-add modifiers, parlour kiosks, and loyalty for your sweet regulars.',
    rows: [
      { title: 'Modifier-rich billing', mock: 'pos', desc: 'Scoops, toppings and combos added in a tap.', points: ['Endless combinations, zero slowdown.', 'Quick re-order of favourites.'] },
      { title: 'Parlour self-kiosks', mock: 'kiosk', desc: 'Let guests build their own dessert and pay.', points: ['Visual builder boosts ticket size.', 'Frees staff to serve.'] },
      { title: 'Seasonal menu control', mock: 'business', desc: 'Flip flavours and specials across outlets instantly.', points: ['Schedule limited-time flavours.', 'Hide sold-out items live.'] },
    ] },
};

/* ============================== INTEGRATIONS ============================== */
const INTEGRATION_PAGES = {
  'easebuzz': { name: 'Easebuzz', icon: 'wallet', category: 'Payments', dot: '#5B2EE0',
    title: 'Collect payments seamlessly with Easebuzz', sub: 'Accept UPI, cards and netbanking with instant settlement and automated reconciliation inside Kaaty.',
    what: ['Real-time UPI confirmation at the counter — no fake screenshots.', 'Automated reconciliation against every order.', 'Instant settlement visibility in your dashboard.'] },
  'razorpay': { name: 'Razorpay', icon: 'credit-card', category: 'Payments', dot: '#0C2451',
    title: 'Power checkout with Razorpay', sub: 'Offer every popular payment method and reconcile each transaction automatically against your Kaaty orders.',
    what: ['UPI, cards, wallets and netbanking out of the box.', 'Payment links for pre-orders and deposits.', 'Auto-matched payouts and settlements.'] },
  'phonepe': { name: 'PhonePe', icon: 'smartphone', category: 'Payments', dot: '#5F259F',
    title: 'Accept PhonePe in a tap', sub: 'Let customers pay with PhonePe UPI and see confirmations land in your ledger in real time.',
    what: ['Instant UPI confirmation, fraud-proof.', 'QR and intent-based payment flows.', 'Reconciled automatically per order.'] },
  'pine-labs': { name: 'Pine Labs', icon: 'printer', category: 'Hardware', dot: '#0B7F5B',
    title: 'Deep native Pine Labs integration', sub: 'Run billing, card processing and receipts from a single Pine Labs smart Android terminal.',
    what: ['Look up mobile orders on the terminal.', 'Process cards and print receipts in one device.', 'No double entry between POS and terminal.'] },
  'thermal-printers': { name: 'Thermal Printers', icon: 'printer', category: 'Hardware', dot: '#475569',
    title: 'Works with any thermal printer', sub: 'Print itemised bills, KOTs and tokens on standard thermal and kitchen printers — wired or Bluetooth.',
    what: ['Auto-print KOTs to the right station.', 'Customisable bill and token layouts.', 'Bluetooth printing from mobile devices.'] },
  'swiggy': { name: 'Swiggy', icon: 'bike', category: 'Marketplaces', dot: '#FC8019',
    title: 'Accept Swiggy orders on one screen', sub: 'Pull Swiggy orders straight into Kaaty — accept, bill, KOT and mark ready without app-shuffling.',
    what: ['One-click accept into your POS.', 'Auto-generate KOTs for the kitchen.', 'Mark items out of stock instantly.'] },
  'zomato': { name: 'Zomato', icon: 'utensils', category: 'Marketplaces', dot: '#E23744',
    title: 'Manage Zomato orders inside Kaaty', sub: 'Every Zomato order flows into the same screen as dine-in and QR — no missed tickets, ever.',
    what: ['Unified queue with all channels.', 'Menu and price sync to Zomato.', 'Live stock availability updates.'] },
  'ondc': { name: 'ONDC', icon: 'network', category: 'Marketplaces', dot: '#1F8A5B',
    title: 'Go live on ONDC with Kaaty', sub: 'List your outlet on India’s open network for digital commerce and receive orders directly into Kaaty.',
    what: ['Direct ONDC order ingestion.', 'Commission-light reach to new customers.', 'Same unified order workflow.'] },
};
const INTEGRATION_GROUPS = [
  { label: 'Payments', icon: 'credit-card', items: ['easebuzz', 'razorpay', 'phonepe'] },
  { label: 'Hardware', icon: 'printer', items: ['pine-labs', 'thermal-printers'] },
  { label: 'Marketplaces', icon: 'shopping-bag', items: ['swiggy', 'zomato', 'ondc'] },
];

Object.assign(window, { PRODUCTS, PRODUCT_GROUPS, SOLUTIONS, INTEGRATION_PAGES, INTEGRATION_GROUPS, SHARED_BENEFIT_FAQS });
